version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accidents_raw
    volumes:
       - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-marc.christensen1@marist.edu}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - database_data:/var/lib/postgresql/data
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  webservice:
    image: marcchristensen/mscsproject:latest
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - postgres
      - pgadmin
    networks:
      - postgres
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  database_data:
  pgadmin:
